### ISSUE TITLE
Serial 1 is not functional

### ISSUE THREAD

**Issue by steamboating** [AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule#8]
I like this attempt to integrate the D21J into the Arduino world - it is already a great help for me. I could connect a display by SPI already.

![dsc01563-k](https://cloud.githubusercontent.com/assets/1594017/22628466/c4aac1ee-ebd4-11e6-8e52-b050a44feb22.jpg)

In the moment I am struggling with Serial1 
It don't work for me.

In the variant,h for the VARIANT_ATMEL_SAMD21_XPRO_V1 I found this entry:
extern Uart Serial;

But nothing related to the Serial1

Any help with that?

**Comment by steamboating** [comment]
Just a question for a better understanding.
In which files does this code differs from the arduino zero file?
I know already:
variant.cpp
variant.h
wiring_analog.c.

If you could get me the list of different files I maybe would be able to figure out the rest.

Does the boot-loader differ from the zero? If so, could you please upload that code also!

Thanks a lot
Rainer

**Comment by zrecore** [comment]
Have you tried defining Serial as SerialUSB? See
https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/blob/master/module/variants/atmel_samr21_xpro/variant.h


To use "Serial.print()" etc...

Somewhere at the top of your sketch (after including Wire.h), add:

#define Serial SERIAL_PORT_USBVIRTUAL

**Comment by steamboating** [comment]
Yes, serial USB is running perfect but I can not connect through the D21J to the Serial port of the connected ESP with your solution.

I used the ordinary Arduino Zero Definition and was able to speak via the SerialUSB to the ESP connected to the xplained board. So it seems to be a problem with my installation of your software or your software.

I will try out your hint with the
#define Serial SERIAL_PORT_USBVIRTUAL
later.

In the moment I just added some Digital pin definitions to the original zero variant.cpp and this works to reach the additional 14 pins!

Could you please tell me if the Zero and your solution are using different boot-loader - or is this boot-loader an universal piece of code for all D21x chips?

Thanks a lot for any support,
Rainer

PS:
I will build a new PCB for my Wood-Walker Robot with the SAMD21J which is powered by the Atmel SAM3X8 in the moment.

Have a look at:
http://wood-walker.com/de/

**Comment by aethaniel** [comment]
Hi, sorry, it seems I missed some issues here :-(

The SAMD21-XPRO variant is not implemented in the same way as Arduino Zero, mainly due to the different form factor and Xplained Pro connectors.

This module has been used in University classes without problem, so far.
I improved recently the documentation in the wiki but I totally forgot to add the variant pinout...

You can check meanwhile this document which contains the pinout in a friendly manner: https://github.com/AtmelUniversityFrance/StartupWeekendAixMarseille_201610/blob/master/SWAM_october2016.pptx

**Comment by aethaniel** [comment]
@steamboating, @zrecore, I have updated wiki by adding the Arduino-friendly pinout coming with this module: https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/wiki/GettingStarted:-SAMD21-Xplained-Pro

fixed by https://github.com/AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule/commit/1630cf2ea4cf0718d22cce94a728fd89b2e8fe31
