### ISSUE TITLE
SAML22

### ISSUE THREAD

**Issue by zevero** [AtmelUniversityFrance/atmel-samd21-xpro-boardmanagermodule#9]
As I am not so experienced with all those new variants ... and as I am struggling a bit with Atmel ASF, having quite some Arduino Background... Is there a chance for me to adapt samd to saml somehow?

**Comment by aethaniel** [comment]
Hi @zevero, yes there is a chance if you have a great motivation and some months to put on this due to all differences between the products.
If I remember well an estimation I did few months ago, only I/O port, USB and Timer counter have similar interfaces. The clock system would need some time too. 
You have to take into account the tools needed to program/debug the Arduino APIs and later on used for applications from Arduino IDE.

Nothing is impossible once you know what need to be done and how. I didn't know anything about SAM D21 when I collaborated on Arduino Zero port. It took 4-5 months, roughly, before having something fully usable to give to community.

**Comment by zevero** [comment]
Thank you for your kind words. I am willing to put in some days but not months. I will try how far I get once I get my SAML22 Xplained pro ...
LCD driver and energy management will not be easy I guess ...
